---
- name: Update APT Cache
  apt:
    update_cache: yes
  register: apt_update_result
  retries: 3
  delay: 15
  until: apt_update_result is succeeded
  ignore_errors: yes

- name: Install Essential Packages
  apt:
    state: present
    force: yes
    pkg:
      - build-essential
      - git
      - htop
      - libcrypto++-dev
      - libssl-dev
      - ntp
      - python3-dev
      - python3-pip
      - virtualenv
      - redis-server
      - screen
      - supervisor
      - vim
      - acl
      - zlib1g-dev
